language: swift
osx_image: xcode11.1
before_install:
  - brew install python
  - brew install bluepill --HEAD
  - pip install requests
script:
  - mkdir output_directory
  - xcodebuild build-for-testing -scheme standard-swift -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
  - ls
  - cd 
  - cd /Users/travis/Library/Developer/Xcode/DerivedData/
  - ls
  - cd  "$(\ls -1dt ./*/ | head -n 1)"
  - ls -R 
  #- bluepill --xctestrun-path standard-swift_iphonesimulator10.3-x86_64.xctestrun -o output_directory
  #- bash <(curl -s https://codecov.io/bash)