language: swift
osx_image: xcode11.1
before_install:
  - brew install python
  - brew install bluepill --HEAD
  - pip install requests
script:
  - mkdir output_directory
  - xcodebuild build-for-testing -scheme standard-swift -sdk iphonesimulator build-for-testing 
  - ls
  - bluepill --xctestrun-path standard-swift_iphonesimulator10.3-x86_64.xctestrun -o output_directory
  - bash <(curl -s https://codecov.io/bash)