language: swift
osx_image: xcode11.1
before_install:
  - brew install python
  - brew install bluepill --HEAD
  - pip install requests
script:
  - mkdir output_directory
  - xcodebuild build-for-testing -scheme standard-swift -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
  - cd 
  - cd /Users/travis/Library/Developer/Xcode/DerivedData/
  - cd  "$(\ls -1dt ./*/ | head -n 1)"
  - cd Build/Products
  - filePath=$(pwd)/standard-swift_iphonesimulator13.1-x86_64.xctestrun
  - bluepill --xctestrun-path $filePath -o output_directory
  #- bash <(curl -s https://codecov.io/bash)