language: swift
osx_image: xcode11.1
before_install:
  - brew install python
  - brew install bluepill --HEAD
  - pip install requests
script:
  - mkdir output_directory
  - xcodebuild build-for-testing -scheme standard-swift -sdk iphonesimulator build-for-testing -derivedDataPath .
  - ls
  - bluepill -s standard-swift.xcscheme -o output_directory 
  - bash <(curl -s https://codecov.io/bash) 
