language: swift
osx_image: xcode11.1
before_install:
  - brew install python
  - brew install bluepill --HEAD
  - pip install requests
script:
  - xcodebuild build-for-testing -scheme standard-swift -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' 
  - ls
  - bluepill --xctestrun-path standard-swift_iphonesimulator13.1-x86_64.xctestrun -o ./output/
  - bash <(curl -s https://codecov.io/bash) 
